# mypy: ignore-errors
# generated by datamodel-codegen:
#   filename:  boxcompute-v2.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class AccountStatus(Enum):
    active = 'active'
    frozen = 'frozen'


class ExpiringPromo(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    micros: conint(ge=-9007199254740991, le=9007199254740991)
    expires_at: conint(ge=0, le=9007199254740991) = Field(..., alias='expiresAt')


class Balance(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    cash_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(..., alias='cashMicros')
    promo_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='promoMicros'
    )
    plan_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(..., alias='planMicros')
    total_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='totalMicros'
    )
    available_micros: conint(ge=-9007199254740991, le=9007199254740991) | None = Field(
        ..., alias='availableMicros'
    )
    """
    Spendable credit after holds and running compute; null when compute estimates are unavailable.
    """
    reserved_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='reservedMicros'
    )
    expiring_promo: ExpiringPromo | None = Field(..., alias='expiringPromo')


class SettledUsage(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    ai_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(..., alias='aiMicros')
    sandbox_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='sandboxMicros'
    )
    total_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='totalMicros'
    )


class Status(Enum):
    available = 'available'
    not_applicable = 'not_applicable'
    unavailable = 'unavailable'


class ActiveEstimate(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    status: Status
    as_of: str | None = Field(..., alias='asOf')
    runtime_seconds: confloat(ge=0.0) = Field(..., alias='runtimeSeconds')
    billable_seconds: confloat(ge=0.0) = Field(..., alias='billableSeconds')
    amount_micros: conint(ge=-9007199254740991, le=9007199254740991) | None = Field(
        ..., alias='amountMicros'
    )


class ModelBillingMode(Enum):
    observe = 'observe'
    enforced = 'enforced'


class BillingSummary(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    currency: Literal['usd']
    account_status: AccountStatus = Field(..., alias='accountStatus')
    balance: Balance
    settled_usage: SettledUsage = Field(..., alias='settledUsage')
    """
    All-time verified wallet deductions for AI and compute. Excludes holds, running estimates and observed AI costs.
    """
    active_estimate: ActiveEstimate = Field(..., alias='activeEstimate')
    model_billing_mode: ModelBillingMode = Field(..., alias='modelBillingMode')


class Bucket(Enum):
    cash = 'cash'
    promo = 'promo'
    plan = 'plan'


class BillingTransaction(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    kind: str
    bucket: Bucket
    amount_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='amountMicros'
    )
    description: str
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')
    expires_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='expiresAt')


class Transaction(BillingTransaction):
    pass


class BillingTransactionPage(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    currency: Literal['usd']
    transactions: list[Transaction] = Field(..., max_length=200)
    next_cursor: str | None = Field(..., alias='nextCursor')


class StartSandboxRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )


class Port(RootModel[conint(ge=1, le=65535)]):
    root: conint(ge=1, le=65535)


class ServiceAccessRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        regex_engine="python-re",
    )
    requested_at: conint(le=9007199254740991, gt=0)
    client_key: constr(pattern=r'^nodekey:(?!0{64}$)[a-f0-9]{64}$')
    recipient_key: constr(pattern=r'^[A-Za-z0-9+/]{43}=$')
    ports: list[Port] = Field(..., max_length=8, min_length=1)


class ServiceAccessId(
    RootModel[constr(pattern=r'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$')]
):
    root: constr(pattern=r'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$')


class ServiceAccessEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    generation_id: constr(pattern=r'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$')
    expires_at: conint(le=9007199254740991, gt=0)
    sealed: constr(min_length=80, max_length=16000)


class Cleanup(Enum):
    guardian_confirmed = 'guardian-confirmed'
    untrusted_guest_report = 'untrusted-guest-report'


class ServiceAccessRevoke(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    generation_id: str
    cleanup: Cleanup


class CooperativeConnectionKeys(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        regex_engine="python-re",
    )
    client_key: constr(pattern=r'^nodekey:(?!0{64}$)[a-f0-9]{64}$')
    ssh_key: constr(pattern=r'^ssh-ed25519 [A-Za-z0-9+/]{68}$')
    recipient_key: constr(pattern=r'^[A-Za-z0-9+/]{43}=$')


class CooperativeEndpointId(ServiceAccessId):
    pass


class CooperativeEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    endpoint_id: constr(pattern=r'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$')
    expires_at: conint(le=9007199254740991, gt=0)
    sealed: constr(pattern=r'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$', min_length=80, max_length=16000)


class CooperativeRevoke(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    endpoint_id: str
    cleanup: Literal['unconfirmed']


class Code(Enum):
    authentication_required = 'AUTHENTICATION_REQUIRED'
    invalid_api_key = 'INVALID_API_KEY'
    insufficient_scope = 'INSUFFICIENT_SCOPE'
    insufficient_credit = 'INSUFFICIENT_CREDIT'
    billing_account_frozen = 'BILLING_ACCOUNT_FROZEN'
    feature_access_denied = 'FEATURE_ACCESS_DENIED'
    invalid_request = 'INVALID_REQUEST'
    invalid_path = 'INVALID_PATH'
    invalid_range = 'INVALID_RANGE'
    invalid_cursor = 'INVALID_CURSOR'
    cursor_stale = 'CURSOR_STALE'
    not_found = 'NOT_FOUND'
    file_not_found = 'FILE_NOT_FOUND'
    destination_exists = 'DESTINATION_EXISTS'
    precondition_failed = 'PRECONDITION_FAILED'
    edit_conflict = 'EDIT_CONFLICT'
    binary_file = 'BINARY_FILE'
    execution_timeout = 'EXECUTION_TIMEOUT'
    payload_too_large = 'PAYLOAD_TOO_LARGE'
    sandbox_unavailable = 'SANDBOX_UNAVAILABLE'
    unsupported_media_type = 'UNSUPPORTED_MEDIA_TYPE'
    unsupported_feature = 'UNSUPPORTED_FEATURE'
    invalid_idempotency_key = 'INVALID_IDEMPOTENCY_KEY'
    idempotency_conflict = 'IDEMPOTENCY_CONFLICT'
    workspace_quota_exceeded = 'WORKSPACE_QUOTA_EXCEEDED'
    service_unavailable = 'SERVICE_UNAVAILABLE'
    rate_limited = 'RATE_LIMITED'


class Error(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    code: Code
    error: str


class Workspace(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    name: str
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')


class Account(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    email: str | None
    name: str | None


class ApiKey(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    name: str
    scopes: list[str] = Field(..., min_length=1)
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')
    last_used_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='lastUsedAt')


class Me(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    account: Account
    api_key: ApiKey = Field(..., alias='apiKey')


class CreateWorkspaceRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    name: constr(pattern=r'\S', min_length=1, max_length=80)


class State(Enum):
    cold = 'cold'
    pending = 'pending'
    running = 'running'
    expired = 'expired'


class Size(Enum):
    small = 'small'
    large = 'large'


class Sandbox(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    workspace_id: str = Field(..., alias='workspaceId')
    name: str
    state: State
    vm_sandbox: bool = Field(..., alias='vmSandbox')
    block_network: bool | None = Field(None, alias='blockNetwork')
    """
    Immutable VM network intent: true means no NIC; false means Internet. Omitted for non-VM sandboxes and historical replay responses.
    """
    size: Size | None = None
    """
    Immutable VM resource profile. Omitted for historical replay responses written before the selector existed; those rows are small.
    """
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')
    last_used_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='lastUsedAt')


class CreateSandboxRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    workspace_id: constr(pattern=r'\S', min_length=1) = Field(..., alias='workspaceId')
    name: constr(pattern=r'\S', min_length=1, max_length=80) | None = None
    vm_sandbox: bool | None = Field(True, alias='vmSandbox')
    """
    Runtime selection. Omitted or true creates a VM sandbox (fixed image; no volumes, libraries or image override); false creates a gVisor container sandbox. An explicit vmSandbox:true requires an Idempotency-Key header; an omitted vmSandbox may create keyless, in which case the server generates the key. Historical idempotency replays retain their original runtime.
    """
    block_network: bool | None = Field(None, alias='blockNetwork')
    """
    VM only: defaults to false (Internet) for new requests; true selects no NIC. Ignored for non-VM sandboxes. Historical idempotency replays retain their original blocked intent.
    """
    size: Size | None = 'small'
    """
    VM only: resource profile. Omitted or "small" is 0.5 vCPU / 1024 MiB; "large" is 1.5 vCPU / 3072 MiB. Both default to a 30 GiB thin-provisioned workspace. "small" is ignored for gVisor sandboxes and "large" is rejected with INVALID_ARGUMENT. Historical idempotency replays retain their original size and workspace capacity.
    """


class ArgvItem(RootModel[constr(min_length=1, max_length=8192)]):
    root: constr(min_length=1, max_length=8192)


class ExecuteRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    argv: list[ArgvItem] = Field(..., max_length=64, min_length=1)
    cwd: constr(pattern=r'^\/workspace(?:\/.*)?$') | None = '/workspace'
    env: dict[constr(pattern=r'^[A-Za-z_][A-Za-z0-9_]*$'), str] | None = Field(None, max_length=64)
    timeout_seconds: conint(ge=1, le=900) | None = Field(120, alias='timeoutSeconds')
    max_output_bytes: conint(ge=1, le=1048576) | None = Field(262144, alias='maxOutputBytes')


class CreatePreviewRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    port: conint(ge=1, le=65535)


class Preview(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    preview_id: constr(pattern=r'^[a-f0-9]{32}$') = Field(..., alias='previewId')
    sandbox_id: str = Field(..., alias='sandboxId')
    port: conint(ge=1, le=65535)
    url: AnyUrl
    expires_at: AwareDatetime = Field(..., alias='expiresAt')


class StartOperationRequest(ExecuteRequest):
    pass


class ExecutionResult(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    stdout: str
    stderr: str
    exit_code: conint(ge=-9007199254740991, le=9007199254740991) = Field(..., alias='exitCode')
    timed_out: bool = Field(..., alias='timedOut')
    stdout_truncated: bool = Field(..., alias='stdoutTruncated')
    stderr_truncated: bool = Field(..., alias='stderrTruncated')


class State1(Enum):
    accepted = 'accepted'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    timed_out = 'timedOut'
    cancelled = 'cancelled'


class Operation(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    operation_id: constr(pattern=r'^op_[a-f0-9]{32}$') = Field(..., alias='operationId')
    state: State1
    exit_code: conint(ge=-9007199254740991, le=9007199254740991) | None = Field(
        ..., alias='exitCode'
    )
    signal: str | None
    accepted_at: AwareDatetime = Field(..., alias='acceptedAt')
    started_at: AwareDatetime | None = Field(..., alias='startedAt')
    finished_at: AwareDatetime | None = Field(..., alias='finishedAt')
    stdout_offset: conint(ge=0, le=9007199254740991) = Field(..., alias='stdoutOffset')
    stderr_offset: conint(ge=0, le=9007199254740991) = Field(..., alias='stderrOffset')
    expires_at: AwareDatetime | None = Field(..., alias='expiresAt')


class Operation1(Operation):
    pass


class OperationResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    operation: Operation1


class Stream(Enum):
    stdout = 'stdout'
    stderr = 'stderr'


class OperationOutputChunk(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    stream: Stream
    data_base64: str = Field(..., alias='dataBase64')
    offset: conint(ge=0, le=9007199254740991)
    next_offset: conint(ge=0, le=9007199254740991) = Field(..., alias='nextOffset')
    earliest_offset: conint(ge=0, le=9007199254740991) = Field(..., alias='earliestOffset')
    truncated: bool


class WaitOperationRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    timeout_seconds: conint(ge=0, le=30) | None = Field(30, alias='timeoutSeconds')


class Source(Enum):
    workload = 'workload'
    execute = 'execute'
    process = 'process'


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    timestamp: str
    stream: Stream
    source: Source
    message: str


class SandboxLogs(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    sandbox_id: str = Field(..., alias='sandboxId')
    entries: list[Entry]
    truncated: bool
    retention_seconds: conint(ge=0, le=9007199254740991)


class DeletedVia(Enum):
    console = 'console'
    api = 'api'
    agent = 'agent'
    workspace = 'workspace'


class DeletedSandbox(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    sandbox_id: str = Field(..., alias='sandboxId')
    name: str
    workspace_id: str = Field(..., alias='workspaceId')
    workspace_name: str | None = Field(..., alias='workspaceName')
    vm_sandbox: bool = Field(..., alias='vmSandbox')
    size: str
    runtimes: list[str]
    deleted_via: DeletedVia = Field(..., alias='deletedVia')
    deleted_by_api_key_id: str | None = Field(..., alias='deletedByApiKeyId')
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')
    last_used_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='lastUsedAt')
    deleted_at: conint(ge=0, le=9007199254740991) = Field(..., alias='deletedAt')


class Totals(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    runs: conint(ge=0, le=9007199254740991)
    billable_seconds: conint(ge=0, le=9007199254740991) = Field(..., alias='billableSeconds')
    settled_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='settledMicros'
    )
    estimated_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='estimatedMicros'
    )


class ApiKey2(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    name: str
    hint: str
    revoked: bool


class ApiKey1(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    runs: conint(ge=0, le=9007199254740991)
    billable_seconds: conint(ge=0, le=9007199254740991) = Field(..., alias='billableSeconds')
    settled_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='settledMicros'
    )
    estimated_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='estimatedMicros'
    )
    api_key: ApiKey2 | None = Field(..., alias='apiKey')
    sandboxes: conint(ge=0, le=9007199254740991)


class Sandbox1(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    runs: conint(ge=0, le=9007199254740991)
    billable_seconds: conint(ge=0, le=9007199254740991) = Field(..., alias='billableSeconds')
    settled_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='settledMicros'
    )
    estimated_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='estimatedMicros'
    )
    id: str
    sandbox_id: str = Field(..., alias='sandboxId')
    name: str
    deleted: bool
    vm_sandbox: bool = Field(..., alias='vmSandbox')
    size: str
    created_by_api_key_id: str | None = Field(..., alias='createdByApiKeyId')
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')
    deleted_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='deletedAt')
    first_started_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='firstStartedAt')
    last_ended_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='lastEndedAt')


class Unattributed(Totals):
    pass


class SandboxCostReport(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    from_: conint(ge=0, le=9007199254740991) = Field(..., alias='from')
    to: conint(ge=0, le=9007199254740991)
    currency: Literal['usd']
    estimates: Status
    totals: Totals
    api_keys: list[ApiKey1] = Field(..., alias='apiKeys')
    sandboxes: list[Sandbox1]
    unattributed: Unattributed


class CreatedByApiKey(ApiKey2):
    pass


class Run(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    started_at: conint(ge=0, le=9007199254740991) = Field(..., alias='startedAt')
    ended_at: conint(ge=0, le=9007199254740991) = Field(..., alias='endedAt')
    runtime_seconds: conint(ge=0, le=9007199254740991) = Field(..., alias='runtimeSeconds')
    billable_seconds: conint(ge=0, le=9007199254740991) = Field(..., alias='billableSeconds')
    rate_micros_per_minute: conint(ge=0, le=9007199254740991) = Field(
        ..., alias='rateMicrosPerMinute'
    )
    amount_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='amountMicros'
    )


class RunningItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    started_at: conint(ge=0, le=9007199254740991) = Field(..., alias='startedAt')
    billable_seconds: conint(ge=0, le=9007199254740991) = Field(..., alias='billableSeconds')
    estimated_micros: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias='estimatedMicros'
    )


class SandboxCostDetail(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    sandbox: Sandbox1
    created_by_api_key: CreatedByApiKey | None = Field(..., alias='createdByApiKey')
    currency: Literal['usd']
    estimates: Status
    runs: list[Run] = Field(..., max_length=1000)
    running: list[RunningItem]
    truncated: bool


class DeletedSandbox1(DeletedSandbox):
    pass


class DeletedSandboxList(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    deleted_sandboxes: list[DeletedSandbox1] = Field(..., alias='deletedSandboxes', max_length=100)


class WorkspacePath(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^\/workspace(?:\/(?!\.{1,2}(?:\/|$))[^/\0]+)*$', max_length=4096)


class Kind(Enum):
    file = 'file'
    dir = 'dir'
    other = 'other'


class FileStat(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        regex_engine="python-re",
    )
    path: constr(pattern=r'^\/workspace(?:\/(?!\.{1,2}(?:\/|$))[^/\0]+)*$', max_length=4096)
    kind: Kind
    is_symbolic_link: bool = Field(..., alias='isSymbolicLink')
    size: conint(ge=0, le=9007199254740991)
    mtime_ms: confloat(ge=0.0) = Field(..., alias='mtimeMs')


class File(FileStat):
    pass


class FileStatResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    file: File


class Kind2(Enum):
    file = 'file'
    dir = 'dir'
    symlink = 'symlink'
    other = 'other'


class FileListEntry(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        regex_engine="python-re",
    )
    name: str
    path: constr(pattern=r'^\/workspace(?:\/(?!\.{1,2}(?:\/|$))[^/\0]+)*$', max_length=4096)
    kind: Kind2
    size: conint(ge=0, le=9007199254740991)
    mtime_ms: confloat(ge=0.0) = Field(..., alias='mtimeMs')


class Entry1(FileListEntry):
    pass


class FileList(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    entries: list[Entry1] = Field(..., max_length=1000)
    next_cursor: str | None = Field(..., alias='nextCursor')


class CreateDirectoryRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    recursive: bool | None = False


class RenameFileRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        regex_engine="python-re",
    )
    destination: constr(pattern=r'^\/workspace(?:\/(?!\.{1,2}(?:\/|$))[^/\0]+)*$', max_length=4096)
    overwrite: bool


class EditFileRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    expected_sha256: constr(pattern=r'^[a-f0-9]{64}$') = Field(..., alias='expectedSha256')
    old_text: constr(min_length=1, max_length=65536) = Field(..., alias='oldText')
    new_text: constr(max_length=65536) = Field(..., alias='newText')
    replace_all: bool = Field(..., alias='replaceAll')


class EditFileResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    sha256: constr(pattern=r'^[a-f0-9]{64}$')


class Action(Enum):
    sandbox_start = 'sandbox.start'
    sandbox_inspect = 'sandbox.inspect'
    sandbox_execute = 'sandbox.execute'
    sandbox_delete = 'sandbox.delete'
    sandbox_file_read = 'sandbox.file.read'
    sandbox_file_write = 'sandbox.file.write'
    sandbox_file_stat = 'sandbox.file.stat'
    sandbox_file_list = 'sandbox.file.list'
    sandbox_file_mkdir = 'sandbox.file.mkdir'
    sandbox_file_rename = 'sandbox.file.rename'
    sandbox_file_edit = 'sandbox.file.edit'
    sandbox_file_remove = 'sandbox.file.remove'


class RecentItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    workspace_id: str = Field(..., alias='workspaceId')
    sandbox_id: str | None = Field(..., alias='sandboxId')
    action: Action
    duration_ms: conint(ge=0, le=9007199254740991) = Field(..., alias='durationMs')
    output_bytes: conint(ge=0, le=9007199254740991) = Field(..., alias='outputBytes')
    success: bool
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    since: conint(ge=0, le=9007199254740991)
    operations: conint(ge=0, le=9007199254740991)
    executions: conint(ge=0, le=9007199254740991)
    execution_time_ms: conint(ge=0, le=9007199254740991) = Field(..., alias='executionTimeMs')
    output_bytes: conint(ge=0, le=9007199254740991) = Field(..., alias='outputBytes')
    failed_operations: conint(ge=0, le=9007199254740991) = Field(..., alias='failedOperations')
    agent_runs: conint(ge=0, le=9007199254740991) = Field(..., alias='agentRuns')
    tool_calls: conint(ge=0, le=9007199254740991) = Field(..., alias='toolCalls')
    active_sandboxes: conint(ge=0, le=9007199254740991) = Field(..., alias='activeSandboxes')
    sandbox_slots: conint(ge=0, le=9007199254740991) = Field(..., alias='sandboxSlots')
    recent: list[RecentItem] = Field(..., max_length=20)


class Type(Enum):
    api_request = 'api.request'
    api_key_created = 'api_key.created'
    api_key_revoked = 'api_key.revoked'
    api_key_rejected = 'api_key.rejected'


class Type1(Enum):
    api_key = 'api_key'
    session = 'session'


class ApiKey3(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    name: str | None
    hint: str | None


class Actor(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    type: Type1
    api_key: ApiKey3 | None = Field(..., alias='apiKey')
    ip_address: str | None = Field(..., alias='ipAddress')
    user_agent: str | None = Field(..., alias='userAgent')


class Request(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    method: str
    route: str | None
    path: str
    status: conint(ge=-9007199254740991, le=9007199254740991)
    duration_ms: conint(ge=0, le=9007199254740991) = Field(..., alias='durationMs')


class AuditEvent(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    type: Type
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')
    request_id: str | None = Field(..., alias='requestId')
    actor: Actor
    request: Request | None
    resource_id: str | None = Field(..., alias='resourceId')


class Actor1(Actor):
    pass


class Event(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    type: Type
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')
    request_id: str | None = Field(..., alias='requestId')
    actor: Actor1
    request: Request | None
    resource_id: str | None = Field(..., alias='resourceId')


class AuditEventPage(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    events: list[Event] = Field(..., max_length=200)
    next_cursor: str | None = Field(..., alias='nextCursor')


class RuntimeClass(Enum):
    container = 'container'
    vm = 'vm'


class Generation(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    generation: conint(le=9007199254740991, gt=0)
    runtime_class: RuntimeClass = Field(..., alias='runtimeClass')
    started_at: conint(ge=0, le=9007199254740991) = Field(..., alias='startedAt')
    ready_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='readyAt')
    stopped_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='stoppedAt')
    finalized_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='finalizedAt')
    startup_duration_ms: conint(ge=0, le=9007199254740991) | None = Field(
        ..., alias='startupDurationMs'
    )
    runtime_duration_ms: conint(ge=0, le=9007199254740991) | None = Field(
        ..., alias='runtimeDurationMs'
    )


class Operation2(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    bucket_start: conint(ge=0, le=9007199254740991) = Field(..., alias='bucketStart')
    generation: conint(le=9007199254740991, gt=0) | None
    operations: conint(ge=0, le=9007199254740991)
    executions: conint(ge=0, le=9007199254740991)
    duration_ms: conint(ge=0, le=9007199254740991) = Field(..., alias='durationMs')
    execution_duration_ms: conint(ge=0, le=9007199254740991) = Field(
        ..., alias='executionDurationMs'
    )
    output_bytes: conint(ge=0, le=9007199254740991) = Field(..., alias='outputBytes')
    failures: conint(ge=0, le=9007199254740991)


class Status1(Enum):
    available = 'available'
    partial = 'partial'
    unavailable = 'unavailable'
    not_configured = 'not_configured'


class Coverage(Enum):
    available = 'available'
    partial = 'partial'
    expired = 'expired'


class Metric(Enum):
    cpu_usage_cores = 'cpu_usage_cores'
    memory_working_set_bytes = 'memory_working_set_bytes'
    network_receive_bytes_per_second = 'network_receive_bytes_per_second'
    network_transmit_bytes_per_second = 'network_transmit_bytes_per_second'
    filesystem_read_bytes_per_second = 'filesystem_read_bytes_per_second'
    filesystem_write_bytes_per_second = 'filesystem_write_bytes_per_second'
    filesystem_usage_bytes = 'filesystem_usage_bytes'
    restarts_total = 'restarts_total'
    oom_kills_total = 'oom_kills_total'


class Unit(Enum):
    cores = 'cores'
    bytes = 'bytes'
    bytes_per_second = 'bytes_per_second'
    count = 'count'


class Availability(Enum):
    available = 'available'
    no_data = 'no_data'


class Series(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    generation: conint(le=9007199254740991, gt=0)
    metric: Metric
    unit: Unit
    availability: Availability
    points: list[list[Any]] = Field(..., max_length=1001)


class Resources(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    status: Status1
    coverage: Coverage
    retention_start: conint(ge=0, le=9007199254740991) = Field(..., alias='retentionStart')
    series: list[Series] = Field(..., max_length=9)


class SandboxAnalytics(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    sandbox_id: str = Field(..., alias='sandboxId')
    from_: conint(ge=0, le=9007199254740991) = Field(..., alias='from')
    to: conint(ge=0, le=9007199254740991)
    resolution_seconds: conint(ge=60, le=86400) = Field(..., alias='resolutionSeconds')
    retention_seconds: conint(le=9007199254740991, gt=0) = Field(..., alias='retentionSeconds')
    generations_truncated: bool = Field(..., alias='generationsTruncated')
    selected_generation: conint(le=9007199254740991, gt=0) | None = Field(
        ..., alias='selectedGeneration'
    )
    operations_truncated: bool = Field(..., alias='operationsTruncated')
    generations: list[Generation] = Field(..., max_length=32)
    operations: list[Operation2] = Field(..., max_length=1001)
    resources: Resources
