# mypy: ignore-errors
# generated by datamodel-codegen:
#   filename:  boxcompute-v2.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Code(Enum):
    authentication_required = 'AUTHENTICATION_REQUIRED'
    invalid_api_key = 'INVALID_API_KEY'
    insufficient_scope = 'INSUFFICIENT_SCOPE'
    invalid_request = 'INVALID_REQUEST'
    invalid_path = 'INVALID_PATH'
    invalid_range = 'INVALID_RANGE'
    invalid_cursor = 'INVALID_CURSOR'
    cursor_stale = 'CURSOR_STALE'
    not_found = 'NOT_FOUND'
    file_not_found = 'FILE_NOT_FOUND'
    destination_exists = 'DESTINATION_EXISTS'
    precondition_failed = 'PRECONDITION_FAILED'
    edit_conflict = 'EDIT_CONFLICT'
    binary_file = 'BINARY_FILE'
    execution_timeout = 'EXECUTION_TIMEOUT'
    payload_too_large = 'PAYLOAD_TOO_LARGE'
    sandbox_unavailable = 'SANDBOX_UNAVAILABLE'
    unsupported_media_type = 'UNSUPPORTED_MEDIA_TYPE'
    invalid_idempotency_key = 'INVALID_IDEMPOTENCY_KEY'
    idempotency_conflict = 'IDEMPOTENCY_CONFLICT'
    workspace_quota_exceeded = 'WORKSPACE_QUOTA_EXCEEDED'
    service_unavailable = 'SERVICE_UNAVAILABLE'


class Error(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    code: Code
    error: str


class Workspace(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    name: str
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')


class CreateWorkspaceRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    name: constr(pattern=r'\S', min_length=1, max_length=80)


class State(Enum):
    cold = 'cold'
    running = 'running'


class Sandbox(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    workspace_id: str = Field(..., alias='workspaceId')
    name: str
    state: State
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')
    last_used_at: conint(ge=0, le=9007199254740991) | None = Field(..., alias='lastUsedAt')


class CreateSandboxRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    workspace_id: constr(pattern=r'\S', min_length=1) = Field(..., alias='workspaceId')
    name: constr(pattern=r'\S', min_length=1, max_length=80) | None = None


class ArgvItem(RootModel[constr(min_length=1, max_length=8192)]):
    root: constr(min_length=1, max_length=8192)


class ExecuteRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    argv: list[ArgvItem] = Field(..., max_length=64, min_length=1)
    cwd: constr(pattern=r'^\/workspace(?:\/.*)?$') | None = '/workspace'
    env: dict[constr(pattern=r'^[A-Za-z_][A-Za-z0-9_]*$'), str] | None = Field(None, max_length=64)
    timeout_seconds: conint(ge=1, le=900) | None = Field(120, alias='timeoutSeconds')
    max_output_bytes: conint(ge=1, le=1048576) | None = Field(262144, alias='maxOutputBytes')


class StartOperationRequest(ExecuteRequest):
    pass


class ExecutionResult(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    stdout: str
    stderr: str
    exit_code: conint(ge=-9007199254740991, le=9007199254740991) = Field(..., alias='exitCode')
    timed_out: bool = Field(..., alias='timedOut')
    stdout_truncated: bool = Field(..., alias='stdoutTruncated')
    stderr_truncated: bool = Field(..., alias='stderrTruncated')


class State1(Enum):
    accepted = 'accepted'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    timed_out = 'timedOut'
    cancelled = 'cancelled'


class Operation(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    operation_id: constr(pattern=r'^op_[a-f0-9]{32}$') = Field(..., alias='operationId')
    state: State1
    exit_code: conint(ge=-9007199254740991, le=9007199254740991) | None = Field(
        ..., alias='exitCode'
    )
    signal: str | None
    accepted_at: AwareDatetime = Field(..., alias='acceptedAt')
    started_at: AwareDatetime | None = Field(..., alias='startedAt')
    finished_at: AwareDatetime | None = Field(..., alias='finishedAt')
    stdout_offset: conint(ge=0, le=9007199254740991) = Field(..., alias='stdoutOffset')
    stderr_offset: conint(ge=0, le=9007199254740991) = Field(..., alias='stderrOffset')
    expires_at: AwareDatetime | None = Field(..., alias='expiresAt')


class Operation1(Operation):
    pass


class OperationResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    operation: Operation1


class Stream(Enum):
    stdout = 'stdout'
    stderr = 'stderr'


class OperationOutputChunk(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    stream: Stream
    data_base64: str = Field(..., alias='dataBase64')
    offset: conint(ge=0, le=9007199254740991)
    next_offset: conint(ge=0, le=9007199254740991) = Field(..., alias='nextOffset')
    earliest_offset: conint(ge=0, le=9007199254740991) = Field(..., alias='earliestOffset')
    truncated: bool


class WaitOperationRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    timeout_seconds: conint(ge=0, le=30) | None = Field(30, alias='timeoutSeconds')


class Source(Enum):
    workload = 'workload'
    execute = 'execute'
    process = 'process'


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    timestamp: str
    stream: Stream
    source: Source
    message: str


class SandboxLogs(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    sandbox_id: str = Field(..., alias='sandboxId')
    entries: list[Entry]
    truncated: bool
    retention_seconds: conint(ge=0, le=9007199254740991)


class WorkspacePath(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^\/workspace(?:\/(?!\.{1,2}(?:\/|$))[^/\0]+)*$', max_length=4096)


class Kind(Enum):
    file = 'file'
    dir = 'dir'
    other = 'other'


class FileStat(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        regex_engine="python-re",
    )
    path: constr(pattern=r'^\/workspace(?:\/(?!\.{1,2}(?:\/|$))[^/\0]+)*$', max_length=4096)
    kind: Kind
    is_symbolic_link: bool = Field(..., alias='isSymbolicLink')
    size: conint(ge=0, le=9007199254740991)
    mtime_ms: confloat(ge=0.0) = Field(..., alias='mtimeMs')


class File(FileStat):
    pass


class FileStatResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    file: File


class Kind2(Enum):
    file = 'file'
    dir = 'dir'
    symlink = 'symlink'
    other = 'other'


class FileListEntry(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        regex_engine="python-re",
    )
    name: str
    path: constr(pattern=r'^\/workspace(?:\/(?!\.{1,2}(?:\/|$))[^/\0]+)*$', max_length=4096)
    kind: Kind2
    size: conint(ge=0, le=9007199254740991)
    mtime_ms: confloat(ge=0.0) = Field(..., alias='mtimeMs')


class Entry1(FileListEntry):
    pass


class FileList(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    entries: list[Entry1] = Field(..., max_length=1000)
    next_cursor: str | None = Field(..., alias='nextCursor')


class CreateDirectoryRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    recursive: bool | None = False


class RenameFileRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        regex_engine="python-re",
    )
    destination: constr(pattern=r'^\/workspace(?:\/(?!\.{1,2}(?:\/|$))[^/\0]+)*$', max_length=4096)
    overwrite: bool


class EditFileRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    expected_sha256: constr(pattern=r'^[a-f0-9]{64}$') = Field(..., alias='expectedSha256')
    old_text: constr(min_length=1, max_length=65536) = Field(..., alias='oldText')
    new_text: constr(max_length=65536) = Field(..., alias='newText')
    replace_all: bool = Field(..., alias='replaceAll')


class EditFileResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    sha256: constr(pattern=r'^[a-f0-9]{64}$')


class Action(Enum):
    sandbox_start = 'sandbox.start'
    sandbox_inspect = 'sandbox.inspect'
    sandbox_execute = 'sandbox.execute'
    sandbox_delete = 'sandbox.delete'
    sandbox_file_read = 'sandbox.file.read'
    sandbox_file_write = 'sandbox.file.write'
    sandbox_file_stat = 'sandbox.file.stat'
    sandbox_file_list = 'sandbox.file.list'
    sandbox_file_mkdir = 'sandbox.file.mkdir'
    sandbox_file_rename = 'sandbox.file.rename'
    sandbox_file_edit = 'sandbox.file.edit'
    sandbox_file_remove = 'sandbox.file.remove'


class RecentItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    id: str
    workspace_id: str = Field(..., alias='workspaceId')
    sandbox_id: str | None = Field(..., alias='sandboxId')
    action: Action
    duration_ms: conint(ge=0, le=9007199254740991) = Field(..., alias='durationMs')
    output_bytes: conint(ge=0, le=9007199254740991) = Field(..., alias='outputBytes')
    success: bool
    created_at: conint(ge=0, le=9007199254740991) = Field(..., alias='createdAt')


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    since: conint(ge=0, le=9007199254740991)
    operations: conint(ge=0, le=9007199254740991)
    executions: conint(ge=0, le=9007199254740991)
    execution_time_ms: conint(ge=0, le=9007199254740991) = Field(..., alias='executionTimeMs')
    output_bytes: conint(ge=0, le=9007199254740991) = Field(..., alias='outputBytes')
    failed_operations: conint(ge=0, le=9007199254740991) = Field(..., alias='failedOperations')
    agent_runs: conint(ge=0, le=9007199254740991) = Field(..., alias='agentRuns')
    tool_calls: conint(ge=0, le=9007199254740991) = Field(..., alias='toolCalls')
    active_sandboxes: conint(ge=0, le=9007199254740991) = Field(..., alias='activeSandboxes')
    sandbox_slots: conint(ge=0, le=9007199254740991) = Field(..., alias='sandboxSlots')
    recent: list[RecentItem] = Field(..., max_length=20)
